//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblAssetStatus
//{
//    public int StatusId { get; set; }

//    public string StatusName { get; set; }

//    public virtual ICollection<TblAssetCategory> TblAssetCategories { get; set; } = new List<TblAssetCategory>();

//    public virtual ICollection<TblAsset> TblAssets { get; set; } = new List<TblAsset>();
//}