//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblAuction
//{
//    public int AuctionId { get; set; }

//    public string AuctionNumber { get; set; }

//    public string Title { get; set; }

//    public string Type { get; set; }

//    public DateTime StartDateTime { get; set; }

//    public DateTime EndDateTime { get; set; }

//    public int StatusId { get; set; }

//    public int IncrementalTime { get; set; }

//    public DateTime? CreatedDate { get; set; }

//    public DateTime? UpdatedDate { get; set; }

//    public int? CategoryId { get; set; }

//    public string CreatedBy { get; set; }

//    public string UpdatedBy { get; set; }

//    public string DeletedBy { get; set; }

//    public DateTime? DeletedDate { get; set; }

//    public bool IsDeleted { get; set; }

//    public virtual TblAuctionCategory Category { get; set; }

//    public virtual ICollection<TblAuctionAsset> TblAuctionAssets { get; set; } = new List<TblAuctionAsset>();

//    public virtual ICollection<TblAuctionView> TblAuctionViews { get; set; } = new List<TblAuctionView>();

//    public virtual ICollection<TblBid> TblBids { get; set; } = new List<TblBid>();
//}