//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblAuctionView
//{
//    public int AuctionViewId { get; set; }

//    public int AuctionId { get; set; }

//    public Guid? UserId { get; set; }

//    public DateTime? ViewedAt { get; set; }

//    public virtual TblAuction Auction { get; set; }
//}