//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblAuctionAsset
//{
//    public int AuctionAssetId { get; set; }

//    public int AuctionId { get; set; }

//    public int AssetId { get; set; }

//    public virtual TblAsset Asset { get; set; }

//    public virtual TblAuction Auction { get; set; }
//}