//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblAuctionCategory
//{
//    public int CategoryId { get; set; }

//    public string Name { get; set; }

//    public virtual ICollection<TblAuction> TblAuctions { get; set; } = new List<TblAuction>();
//}