//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblCountry
//{
//    public int CountryId { get; set; }

//    public string CountryName { get; set; }

//    public string PhoneCode { get; set; }

//    public int MinLength { get; set; }

//    public int MaxLength { get; set; }

//    public string SeriesStart { get; set; }

//    public virtual ICollection<TblUser> TblUsers { get; set; } = new List<TblUser>();
//}