//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblDirectSaleSetting
//{
//    public int Id { get; set; }

//    public int? CartItemsLimit { get; set; }

//    public int? CartTimerInMinutes { get; set; }
//}