//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblFinanceSetting
//{
//    public int Id { get; set; }

//    public decimal? Vatpercent { get; set; }

//    public decimal? CreditCardFee { get; set; }

//    public decimal? DebitCardFee { get; set; }

//    public decimal? AdminFees { get; set; }

//    public decimal? AuctionFees { get; set; }

//    public decimal? BuyerCommissionPercent { get; set; }
//}