//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblOtp
//{
//    public int Id { get; set; }

//    public int? UserId { get; set; }

//    public string Code { get; set; }

//    public DateTime? Expiration { get; set; }

//    public bool? IsUsed { get; set; }

//    public virtual TblUser User { get; set; }
//}