//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblRequest
//{
//    public int RequestId { get; set; }

//    public string RequestNumber { get; set; }

//    public int UserId { get; set; }

//    public string Username { get; set; }

//    public string MobileNumber { get; set; }

//    public string Email { get; set; }

//    public int RequestTypeId { get; set; }

//    public int AssetId { get; set; }

//    public int? TransactionId { get; set; }

//    public DateTime RequestDateTime { get; set; }

//    public int RequestStatusId { get; set; }

//    public string CustomerNote { get; set; }

//    public string AdminNote { get; set; }

//    public bool CreatedByAdmin { get; set; }

//    public DateTime CreatedOn { get; set; }

//    public DateTime UpdatedOn { get; set; }

//    public virtual TblAsset Asset { get; set; }

//    public virtual TblRequestStatus RequestStatus { get; set; }

//    public virtual TblRequestType RequestType { get; set; }

//    public virtual TblTransaction Transaction { get; set; }

//    public virtual TblUser User { get; set; }
//}