//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblRequestType
//{
//    public int RequestTypeId { get; set; }

//    public string TypeName { get; set; }

//    public virtual ICollection<TblRequestStatus> TblRequestStatuses { get; set; } = new List<TblRequestStatus>();

//    public virtual ICollection<TblRequest> TblRequests { get; set; } = new List<TblRequest>();
//}