//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblRequestStatus
//{
//    public int RequestStatusId { get; set; }

//    public int RequestTypeId { get; set; }

//    public string StatusName { get; set; }

//    public virtual TblRequestType RequestType { get; set; }

//    public virtual ICollection<TblRequest> TblRequests { get; set; } = new List<TblRequest>();
//}