//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblStaticPagesSetting
//{
//    public int Id { get; set; }

//    public string PrivacyPolicy { get; set; }

//    public string TermsAndConditions { get; set; }

//    public string CookiesPolicy { get; set; }
//}