//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblSystemSetting
//{
//    public int Id { get; set; }

//    public int? GlobalIncrementalTimeInMinutes { get; set; }

//    public DateTime? CreatedAt { get; set; }

//    public DateTime? UpdatedAt { get; set; }
//}