//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblTransactionDocument
//{
//    public int DocumentId { get; set; }

//    public int TransactionId { get; set; }

//    public string DocumentType { get; set; }

//    public string FilePath { get; set; }

//    public DateTime? UploadedAt { get; set; }

//    public virtual TblTransaction Transaction { get; set; }
//}