//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblTransaction
//{
//    public int TransactionId { get; set; }

//    public string TransactionNumber { get; set; }

//    public decimal Amount { get; set; }

//    public int UserId { get; set; }

//    public int TransactionTypeId { get; set; }

//    public int PaymentMethodId { get; set; }

//    public int? CardTypeId { get; set; }

//    public string MerchantTransactionId { get; set; }

//    public DateTime TransactionDateTime { get; set; }

//    public int StatusId { get; set; }

//    public string Notes { get; set; }

//    public string DocumentPath { get; set; }

//    public long? CreatedByAdminId { get; set; }

//    public DateTime? CreatedAt { get; set; }

//    public DateTime? UpdatedAt { get; set; }

//    public int? CreatedBy { get; set; }

//    public DateTime? CreatedDate { get; set; }

//    public int? UpdatedBy { get; set; }

//    public DateTime? UpdatedDate { get; set; }

//    public int? DeletedBy { get; set; }

//    public DateTime? DeletedDate { get; set; }

//    public bool IsDeleted { get; set; }

//    public virtual TblCardType CardType { get; set; }

//    public virtual TblPaymentMethod PaymentMethod { get; set; }

//    public virtual TblTransactionStatus Status { get; set; }

//    public virtual ICollection<TblRequest> TblRequests { get; set; } = new List<TblRequest>();

//    public virtual ICollection<TblTransactionAsset> TblTransactionAssets { get; set; } = new List<TblTransactionAsset>();

//    public virtual ICollection<TblTransactionDocument> TblTransactionDocuments { get; set; } = new List<TblTransactionDocument>();

//    public virtual TblTransactionType TransactionType { get; set; }

//    public virtual TblUser User { get; set; }
//}