//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblTransactionAsset
//{
//    public int TransactionAssetsId { get; set; }

//    public int TransactionId { get; set; }

//    public int AssetId { get; set; }

//    public decimal? BidPrice { get; set; }

//    public DateTime? CreatedAt { get; set; }

//    public virtual TblAsset Asset { get; set; }

//    public virtual TblTransaction Transaction { get; set; }
//}