//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblTransactionType
//{
//    public int TransactionTypeId { get; set; }

//    public string TransactionTypeName { get; set; }

//    public virtual ICollection<TblTransaction> TblTransactions { get; set; } = new List<TblTransaction>();
//}