//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblUserRole
//{
//    public int UserRoleId { get; set; }

//    public int UserId { get; set; }

//    public int RoleId { get; set; }

//    public DateTime? AssignedAt { get; set; }

//    public virtual TblRole Role { get; set; }

//    public virtual TblUser User { get; set; }
//}