//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblUserStatus
//{
//    public int StatusId { get; set; }

//    public string StatusName { get; set; }

//    public virtual ICollection<TblUser> TblUsers { get; set; } = new List<TblUser>();
//}