//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace AuctionManagementSystem.Domain.model;

//public partial class TblWishlistItem
//{
//    public int WishlistItemId { get; set; }

//    public int UserId { get; set; }

//    public int AssetId { get; set; }

//    public DateTime AddedAt { get; set; }

//    public bool? IsActive { get; set; }

//    public DateTime? DeletedDate { get; set; }

//    public virtual TblAsset Asset { get; set; }

//    public virtual TblUser User { get; set; }
//}