// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuctionManagementSystem.Domain.Entities.Asset;

public partial class TblAssetCategoryPaymentMethod
{
    public int CategoryId { get; set; }

    public int PaymentMethodId { get; set; }

    public int PaymentOptionId { get; set; }

    public virtual TblAssetCategory Category { get; set; }

    public virtual TblAssetPaymentMethod PaymentMethod { get; set; }
}