// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuctionManagementSystem.Domain.Entities.Asset;

public partial class TblAssetPaymentMethod
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<TblAssetCategory> Categories { get; set; } = new List<TblAssetCategory>();
}