// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using AuctionManagementSystem.Domain.Entities.Asset;


namespace AuctionManagementSystem.Domain.Entities.Asset;

public partial class TblAssetCategory
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string Subcategory { get; set; }

    public decimal DepositPercentage { get; set; }

    public string Details { get; set; }

    public decimal AdminFees { get; set; }

    public decimal AuctionFees { get; set; }

    public decimal BuyerCommission { get; set; }

    public DateTime RegistrationDeadline { get; set; }

    public string Icon { get; set; }

    public decimal? Vatpercentage { get; set; }

    public int StatusId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? Vatid { get; set; }

    public virtual TblAssetStatus Status { get; set; }

    public virtual ICollection<TblAsset> TblAssets { get; set; } = new List<TblAsset>();

    public virtual TblVatoption Vat { get; set; }

    public virtual ICollection<TblAssetPaymentMethod> PaymentMethods { get; set; } = new List<TblAssetPaymentMethod>();
}