// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AuctionManagementSystem.Api.Models;

public partial class AuctionManagementDBContext : DbContext
{
    public AuctionManagementDBContext(DbContextOptions<AuctionManagementDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblRole> TblRoles { get; set; }

    public virtual DbSet<TblRolePermissionsMatrix> TblRolePermissionsMatrices { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("AuctionM_dbuser");

        modelBuilder.Entity<TblRole>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__tblRoles__8AFACE1A5E190086");

            entity.ToTable("tblRoles");

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TblRolePermissionsMatrix>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__tblRoleP__8AFACE1A931EC603");

            entity.ToTable("tblRolePermissionsMatrix");

            entity.Property(e => e.RoleId).ValueGeneratedNever();
            entity.Property(e => e.AccessAdminPanel).HasColumnName("Access Admin Panel");
            entity.Property(e => e.ChangeCommission).HasColumnName("Change Commission");
            entity.Property(e => e.ExportReports).HasColumnName("Export Reports");
            entity.Property(e => e.ManageAssets).HasColumnName("Manage Assets");
            entity.Property(e => e.ManageAuctions).HasColumnName("Manage Auctions");
            entity.Property(e => e.ManageCategories).HasColumnName("Manage Categories");
            entity.Property(e => e.ManageRequests).HasColumnName("Manage Requests");
            entity.Property(e => e.ManageRoles).HasColumnName("Manage Roles");
            entity.Property(e => e.ManageTransactions).HasColumnName("Manage Transactions");
            entity.Property(e => e.ManageUsers).HasColumnName("Manage Users");
            entity.Property(e => e.SuperAdmin).HasColumnName("Super Admin");
            entity.Property(e => e.ViewAuditTrail).HasColumnName("View Audit Trail");
            entity.Property(e => e.ViewReports).HasColumnName("View Reports");

            entity.HasOne(d => d.Role).WithOne(p => p.TblRolePermissionsMatrix)
                .HasForeignKey<TblRolePermissionsMatrix>(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblRolePermissionsMatrix_tblRoles");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}