// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuctionManagementSystem.Api.Models;

public partial class TblRolePermissionsMatrix
{
    public int RoleId { get; set; }

    public bool? SuperAdmin { get; set; }

    public bool? AccessAdminPanel { get; set; }

    public bool? ManageAuctions { get; set; }

    public bool? ManageAssets { get; set; }

    public bool? ManageTransactions { get; set; }

    public bool? ManageCategories { get; set; }

    public bool? ManageRoles { get; set; }

    public bool? ManageUsers { get; set; }

    public bool? ViewReports { get; set; }

    public bool? ExportReports { get; set; }

    public bool? ManageRequests { get; set; }

    public bool? ViewAuditTrail { get; set; }

    public bool? ChangeCommission { get; set; }

    public virtual TblRole Role { get; set; }
}