// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuctionManagementSystem.Api.Models;

public partial class TblRole
{
    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public bool IsSeller { get; set; }

    public virtual TblRolePermissionsMatrix TblRolePermissionsMatrix { get; set; }
}