<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contracts\Categories\" />
    <Folder Include="Contracts\Statuses\" />
    <Folder Include="Features\NewFolder\" />
    <Folder Include="Features\Roles\Command\CreateRoles\" />
    <Folder Include="Features\Roles\Command\DeleteRoles\" />
    <Folder Include="Features\Roles\Command\UpdateRoles\" />
    <Folder Include="Features\Roles\Query\GetRoleById\" />
    <Folder Include="Features\Assets\Asset\Command\NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="Hangfire.Core" Version="1.8.18" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="EventStore.Client" Version="22.0.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.4" />
    <PackageReference Include="Stripe.net" Version="48.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuctionManagementSystem.Domain\AuctionManagementSystem.Domain.csproj" />
  </ItemGroup>
</Project>





