// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuctionManagementSystem.Domain.Models;

public partial class TblUserLimitAuditLog
{
    public int AuditLogId { get; set; }

    public int UserId { get; set; }

    public string ActionType { get; set; }

    public decimal? OldDeposit { get; set; }

    public decimal? NewDeposit { get; set; }

    public decimal? OldTotalLimit { get; set; }

    public decimal? NewTotalLimit { get; set; }

    public decimal? OldAvailableLimit { get; set; }

    public decimal? NewAvailableLimit { get; set; }

    public string Notes { get; set; }

    public int? ChangedBy { get; set; }

    public DateTime ChangedDate { get; set; }
}