// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using AuctionManagementSystem.Domain.Entities.Asset;
using AuctionManagementSystem.Domain.Entities.Auction;
using AuctionManagementSystem.Domain.Entities.User;

namespace AuctionManagementSystem.Domain.Entities;

public partial class TblBid
{
    public int BidId { get; set; }

    public int AuctionId { get; set; }

    public int AssetId { get; set; }

    public int UserId { get; set; }

    public decimal BidAmount { get; set; }

    public DateTime BidTime { get; set; }

    public bool? IsWinningBid { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual TblAsset Asset { get; set; }

    public virtual TblAuction Auction { get; set; }

    public virtual TblUser User { get; set; }
}