//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;
//using AuctionManagementSystem.Domain.Entities.Asset;
//using AuctionManagementSystem.Domain.Entities.User;

//namespace AuctionManagementSystem.Domain.Entities;

//public partial class TblCartItem
//{
//    public int CartItemId { get; set; }

//    public int UserId { get; set; }

//    public int AssetId { get; set; }

//    public int Quantity { get; set; }

//    public DateTime AddedAt { get; set; }

//    public bool? IsActive { get; set; }

//    public DateTime? DeletedDate { get; set; }

//    public virtual TblAsset Asset { get; set; }

//    public virtual TblUser User { get; set; }
//}