// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using AuctionManagementSystem.Domain.Entities;
using AuctionManagementSystem.Domain.Entities.Asset;

namespace AuctionManagementSystem.Domain;

public partial class TblVatoption
{
    public int Vatid { get; set; }

    public string Vattype { get; set; }

    public virtual ICollection<TblAssetCategory> TblAssetCategories { get; set; } = new List<TblAssetCategory>();

    public virtual ICollection<TblAsset> TblAssets { get; set; } = new List<TblAsset>();
}