// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using AuctionManagementSystem.Domain.Entities.Asset;

namespace AuctionManagementSystem.Domain;

public partial class TblWinnerAwardingOption
{
    public int AwardingId { get; set; }

    public string AwardingMethod { get; set; }

    public virtual ICollection<TblAsset> TblAssets { get; set; } = new List<TblAsset>();
}